"""salary None

Revision ID: eb83e4738e20
Revises: fedd0d532c3f
Create Date: 2023-12-24 12:03:06.656484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb83e4738e20'
down_revision: Union[str, None] = 'fedd0d532c3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('worker', 'salary',
               existing_type=sa.NUMERIC(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('worker', 'salary',
               existing_type=sa.NUMERIC(),
               nullable=False)
    # ### end Alembic commands ###
