"""live Add Company

Revision ID: ec3c2258be60
Revises: eb83e4738e20
Create Date: 2023-12-27 14:39:44.729982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec3c2258be60'
down_revision: Union[str, None] = 'eb83e4738e20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('begin_shift', 'live')
    op.add_column('company', sa.Column('live', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'live')
    op.add_column('begin_shift', sa.Column('live', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
